# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-89290a7f-57e5-4f09-9011-11207eb27344";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-89290a7f-57e5-4f09-9011-11207eb27344".device =
    "/dev/disk/by-uuid/89290a7f-57e5-4f09-9011-11207eb27344";
  boot.initrd.luks.devices."luks-371db3fb-967f-48b7-ad71-c33836031fe4".device =
    "/dev/disk/by-uuid/371db3fb-967f-48b7-ad71-c33836031fe4";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/16BC-5640";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-371db3fb-967f-48b7-ad71-c33836031fe4"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
